### ISSUE TITLE
ROC plot in the SOLID paper

### ISSUE THREAD

**Issue by snapfinger** [vilsaira/SOLID#1]
Hi Viljami, thanks for your sharing. I wonder how your ROC curve is generated for this outlier detection task? In the SOLID paper, it is mentioned as "calculated by applying modified Z-score thresholds from 0 to 10 ...". However, how each point in the ROC was decided for each Z-score? Is it computed by measuring the percentage of outlier slices correctly identified or not **for each** DWI? Would you open source the code for that part also? Besides, it is said that the experiments were repeated 1000 times, is the number of experiments related to the plotting as well? Thanks.

**Comment by vilsaira** [comment]
Hi Yijun,

Thanks for asking this. The script to do this part is quite messy so I don't quite believe it would be useful to anyone else than me. However, I am happy to detail how the process was done:
1) I estimated diffusion and kurtosis tensors based on [MASSIVE data](http://www.massive-data.org/).
2) I used these tensors to simulate full brain DWIs -> ground truth (GT) of one b0, 30x b1000, and 30x b2000 if I recall correctly.
3) A 'test DWI' set was generated from GT by introducing outlier slices (signal increase / decrease) along with Rician distributed noise to obtain specific SNR. You could also add rotations to the artefactual DWI volumes at this point. Only the randomized outlier position (slice and DWI) was recorded for further use.
4) SOLID was used to calculate the modified Z-scores for each slice in the 'test DWI'. The modified Z-scores were saved for later use. 
5) Steps 3 and 4 were repeated 1000 times i.e. 1000 'test DWIs' in total each with random outlier positions and noise. 
6) The saved outlier positions (step 3) and modified Z-scores (step 4) were used to form the ROC curves. For example, at level mZ = 3.0 all slices with mZ > 3.0 were marked as outliers and this was compared to the known outlier positions to calculate true/false positive/negative findings at that mZ level. If I recall correctly, I looped modified Z-scores from 0 to 10 with step size of 0.1.

I hope this helped!

**Comment by snapfinger** [comment]
Hi Viljami, thanks very much for your detailed explanation! 

If I understand correctly, the way you average the results of the 1000 experiments is first putting all the the predicted outliers together (call it list_outliers), and also saving all the ground truth outliers together (call it list_truth), and then compute the ROC curve from list_outliers and list_truth?

**Comment by vilsaira** [comment]
Hi Yijun,

In short, yes. Simply compare lists of simulated and known outliers to detected outliers to calculate true/false positive/negative findings. Just to make soure, there is no need to average these results at any point. 

Cheers,
 Viljami

**Comment by snapfinger** [comment]
Got it, thanks!
