### ISSUE TITLE
sequence of noise and signal change simulation in SOLID paper

### ISSUE THREAD

**Issue by snapfinger** [vilsaira/SOLID#2]
Hi Viljami, I wonder in your simulations, what is the sequence of signal dropout/increase and noise addition? In the paper it says "For each setup, both a complete signal loss and a modest signal increase artefacts were generated using four SNR levels of Rician noise". However it's not obvious to me whether you first add noise, or you first simulate the dropout? e.g. for a dropout slice, is there still noise, or it's completely blank?

**Comment by vilsaira** [comment]
Hi! First signal decrease/increase and second Rician noise based on B0-signal SNR. This ensures that the noise profile is same in all volumes. If you consider a real measurement with signal drop, the noise would remain in the DWI slice so this is wanted behavior in simulations too.

**Comment by snapfinger** [comment]
Thanks!
